apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: matrix
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "solvoxai"
  DB_USER: "adminuser"
  ENVIRONMENT: "production"
