apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matrix-backend-hpa
  namespace: matrix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matrix-backend

  minReplicas: 2
  maxReplicas: 10

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
