apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: matrix
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-headless

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres
        image: postgres:16

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          value: solvoxai

        - name: POSTGRES_USER
          value: adminuser

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD