---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: backend-secret
  namespace: matrix
spec:
  encryptedData:
    DATABASE_URL: AgCNKUKN4SbeHepIIhQzCvMS5wWmdS2YBGR8mqq6ToSbs4OjVbtKbjcKeGgJ7QnPCJgApdZPdTiK5XfvtGVlCl/CKbpAeiaIu5Cvh3yuXKWaie3qQKOvsGhSeLfCXXLVzrMJ+FM0aCMtCF/qQiHTYNjRzQNQlQCPrwAPGif8CnBApMxvvOlNVOcYCnO8HxRmYzjz4dCTxkkQXFGp3NHeB7CYgcjUhuCk86H+IFBKHyNZPAS62oc7c6zwSQroEcOuG2fO3sxTIzqiO9roUUxRnITOZaqP9cn7Lq/M3uuqbqpaUn0FFc52fGJYQSVqwsQzNvLLK44j5Pat4nYyMQcTWPKWmT5n+tOUfVg7/PyBYfLpaoW1w7vRbv0htrX634Q3EajcP10hDEjtLmDOAhORrt1Z6l8cMryCLenXo+agSzTLzyyZ4iQVbEJegZEwsyLFOcvK6DRuLLb3Z0107jQLw/rh3MOLWMwR4O79wHXzWXtOY2AjhdV3VQ9dqLY1X6yspBJYKIVH9uxX4aPAbH2jcZIdiqVj/tA9ceDv5uNgnh9o/8x5DJFRkGfJB6/Sw3xJV7Lz3zHuLzdefH6AN/QwFfes4wJNRyqwfS5IecIP9QZLS65OUsN0OnAV3QnsKoEUZgbmJ9Es1sVcaTR8aAj6VUQlLexrODv7k17ZjhPSWWYsx2Y6k3LkzT/ReMssdBeZh1z++cSG7nis4IDc5EyKSggsaa0npZB56z9dZclMsxrvK9FTyxABo7Aa6rmiZlx7+Z18t50mzsUu5jA=
    DB_PASSWORD: AgC+IcMo10l67k3xaaBZBPiqHNtbxYQYse6FdB21Mtq4v5yfDFjQkG6NT0MaK9MUp9SRGSFVM/O5AWKsrZVL0ThUgp7oAYze7Y3N6sskCidItZvgnSmwla6AIrhgTFGt4R5pHt31/pFEEmDmdYIIUHyYzNws5aITpW3iVG9axRmLKtO1yu7BNhgreZuymf+Cq35+65pUMDSYW0BPN3X11eHD1CS0++SX9W6Rxjx8rdNwdAqNeTvxQ/fvN/N2M+2+vmBDidcl+4S1HbEXGaZjXQIqOvU1Z1qgSfA35aO/YJvJui4okReoxBCp8qwvwBdBu5KOWakpISHtTqI8T45Mq330NBvCrb2fnZdSV2CxGVEeNuIyBP7OzZT5HQBWWyudIsnw9Umw5tIfFgMCKeccwd3OfmkVYdFxaFsYsv/svPHh4q9MCdsxkDvKREfnDICBQxkL4G4gJG11G0h1KdKojnK2TpUVY5Fv8S3ySCNyrAQDAWCpTXcPRoRlQopecIcdrWSBrNpwnRQkCyk8KTeqepb3lNCOGEPqfauLusCCqQsF5t6nYn55dvX3MgF1UROq2iJAhmQzUl0JmG4JeW7+qKiPEICppiLA3Il6iralspXSHTpBTAVBUYbLDICjj1oT0xk4vAhZbDIqwkKLF5RPgb7dg+u9GrPqp1vaVYzUnyeMDR3Z6OKIsvKUr3jBFJJKIAC4vRshq51yofA11Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: backend-secret
      namespace: matrix
    type: Opaque
